/** @format */

import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import Hero from "../components/Hero";
import SectionOne from "../components/SectionOne";
import SectionTwo from "../components/SectionTwo";
import Footer from "../components/Footer";

const Home = () => {
    return (
        <div>
            <Head>
                <title>DBR DriveClear Front</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <NavBar />
                <Hero />
                <SectionOne />
                <SectionTwo />
                <Footer />
            </main>
        </div>
    );
};

export default Home;
